### ISSUE TITLE
Errors on display.js.org

### ISSUE THREAD

**Issue by 2pha** [arguiot/DisplayJS#5]
When using an adblocker extension in Chrome (Adblock plus in my case) seems to break the display.js.org site.
Seems to be from the video that is embedded and the code served from google to do with ads on the video.

**Comment by arguiot** [comment]
Thank you for submitting this issue, I’ll try to take a look at the code 😊. But could you send me a picture or a video of your screen 📺 (if you don’t know how to do that, there is several software on the internet, simply search on google “screen recorder for `+ your os (Windows 10, macOS, etc...`”), because I have Adblock plus and the website works.

**Comment by 2pha** [comment]
Seems it is not related to AD blocking.
video link: https://www.useloom.com/share/f0a939b99a644b1ebcf0ffda4620ff72

**Comment by arguiot** [comment]
Euh, 😮, this is extremely weird, because I already tried on Chrome and it works fine, so I’m confused 🤷‍♀️, I’ll try to fix it, but I can’t tell what is actually causing that bug. I think 🤔 that your browser ignore some lines, which is weird.

**Comment by arguiot** [comment]
Normally, everything is fixed 👌
